#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECTS_FILE="$ROOT_DIR/projects.json"
RULES_DIR="$ROOT_DIR/rules"

expand_path() {
  local path="$1"
  if [[ "$path" == "~/"* ]]; then
    printf '%s/%s\n' "$HOME" "${path#\~/}"
  else
    printf '%s\n' "$path"
  fi
}

json_value() {
  local js="$1"
  node -e "$js" "$PROJECTS_FILE"
}

project_count="$(json_value 'const fs=require("fs"); const data=JSON.parse(fs.readFileSync(process.argv[1],"utf8")); console.log(data.projects.length);')"

for ((i = 0; i < project_count; i++)); do
  name="$(json_value "const fs=require('fs'); const data=JSON.parse(fs.readFileSync(process.argv[1],'utf8')); console.log(data.projects[$i].name);")"
  raw_path="$(json_value "const fs=require('fs'); const data=JSON.parse(fs.readFileSync(process.argv[1],'utf8')); console.log(data.projects[$i].path);")"
  project_path="$(expand_path "$raw_path")"

  if [[ ! -d "$project_path" ]]; then
    echo "skip: $name ($project_path does not exist)"
    continue
  fi

  mkdir -p "$project_path/.codex"
  codex_output="$project_path/.codex/personal_rules.md"
  claude_output="$project_path/CLAUDE.local.md"

  write_rules() {
    local title="$1"

    echo "# $title"
    echo
    echo "Generated by: $ROOT_DIR/install.sh"
    echo "Project: $name"
    echo
    json_value "const fs=require('fs'); const data=JSON.parse(fs.readFileSync(process.argv[1],'utf8')); console.log(data.projects[$i].rules.join('\n'));" |
      while IFS= read -r rule; do
        rule_path="$RULES_DIR/$rule"
        if [[ ! -f "$rule_path" ]]; then
          echo "missing rule: $rule" >&2
          exit 1
        fi
        echo
        echo "<!-- BEGIN $rule -->"
        cat "$rule_path"
        echo
        echo "<!-- END $rule -->"
      done
  }

  write_rules "Personal Codex Rules" > "$codex_output"
  write_rules "Personal Claude Rules" > "$claude_output"

  if [[ -d "$project_path/.git" ]]; then
    exclude_file="$project_path/.git/info/exclude"
    touch "$exclude_file"
    if ! grep -qxF ".codex/" "$exclude_file"; then
      printf '\n.codex/\n' >> "$exclude_file"
    fi
    if ! grep -qxF "CLAUDE.local.md" "$exclude_file"; then
      printf 'CLAUDE.local.md\n' >> "$exclude_file"
    fi
  fi

  echo "installed: $name"
  echo "  Codex:  $codex_output"
  echo "  Claude: $claude_output"
done
