#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECTS_FILE="$ROOT_DIR/projects.json"
RULES_DIR="$ROOT_DIR/rules"
SKILLS_DIR="$ROOT_DIR/skills"

expand_path() {
  local path="$1"
  if [[ "$path" == "~/"* ]]; then
    printf '%s/%s\n' "$HOME" "${path#\~/}"
  else
    printf '%s\n' "$path"
  fi
}

json_value() {
  local js="$1"
  node -e "$js" "$PROJECTS_FILE"
}

json_has_key() {
  local js="$1"
  node -e "$js" "$PROJECTS_FILE"
}

project_count="$(json_value 'const fs=require("fs"); const data=JSON.parse(fs.readFileSync(process.argv[1],"utf8")); console.log(data.projects.length);')"

for ((i = 0; i < project_count; i++)); do
  name="$(json_value "const fs=require('fs'); const data=JSON.parse(fs.readFileSync(process.argv[1],'utf8')); console.log(data.projects[$i].name);")"
  raw_path="$(json_value "const fs=require('fs'); const data=JSON.parse(fs.readFileSync(process.argv[1],'utf8')); console.log(data.projects[$i].path);")"
  project_path="$(expand_path "$raw_path")"

  if [[ ! -d "$project_path" ]]; then
    echo "skip: $name ($project_path does not exist)"
    continue
  fi

  mkdir -p "$project_path/.codex"
  codex_output="$project_path/.codex/personal_rules.md"
  claude_output="$project_path/CLAUDE.local.md"

  write_rules() {
    local title="$1"

    echo "# $title"
    echo
    echo "Generated by: $ROOT_DIR/install.sh"
    echo "Project: $name"
    echo
    json_value "const fs=require('fs'); const data=JSON.parse(fs.readFileSync(process.argv[1],'utf8')); console.log(data.projects[$i].rules.join('\n'));" |
      while IFS= read -r rule; do
        rule_path="$RULES_DIR/$rule"
        if [[ ! -f "$rule_path" ]]; then
          echo "missing rule: $rule" >&2
          exit 1
        fi
        echo
        echo "<!-- BEGIN $rule -->"
        cat "$rule_path"
        echo
        echo "<!-- END $rule -->"
      done
  }

  write_rules "Personal Codex Rules" > "$codex_output"
  write_rules "Personal Claude Rules" > "$claude_output"

  # AGENTS.override.md: Codex's official discovery reads this before AGENTS.md
  # (same directory, first non-empty file wins), so it is what actually loads
  # our rules into Codex. The original AGENTS.md is inlined first so it is not
  # shadowed. Regenerated fully each run; local-only (git-excluded).
  agents_output="$project_path/AGENTS.override.md"
  {
    echo "<!-- Generated by $ROOT_DIR/install.sh. Local only; do not commit. -->"
    echo "<!-- Codex reads AGENTS.override.md before AGENTS.md, so the repo's own AGENTS.md is inlined below to avoid shadowing it. -->"
    echo
    if [[ -f "$project_path/AGENTS.md" ]]; then
      echo "<!-- BEGIN original AGENTS.md -->"
      cat "$project_path/AGENTS.md"
      echo
      echo "<!-- END original AGENTS.md -->"
      echo
    fi
    write_rules "Personal Codex Rules (from ai-config)"
  } > "$agents_output"

  installed_skills=()
  skill_count="$(json_has_key "const fs=require('fs'); const data=JSON.parse(fs.readFileSync(process.argv[1],'utf8')); console.log((data.projects[$i].skills || []).length);")"
  if [[ "$skill_count" != "0" ]]; then
    mkdir -p "$project_path/skills"
    for ((s = 0; s < skill_count; s++)); do
      skill_name="$(json_value "const fs=require('fs'); const data=JSON.parse(fs.readFileSync(process.argv[1],'utf8')); console.log(data.projects[$i].skills[$s]);")"
      skill_source="$SKILLS_DIR/$skill_name"
      skill_target="$project_path/skills/$skill_name"
      if [[ ! -d "$skill_source" ]]; then
        echo "missing skill: $skill_name" >&2
        exit 1
      fi
      mkdir -p "$skill_target"
      cp -R "$skill_source/." "$skill_target/"
      installed_skills+=("skills/$skill_name/")
    done
  fi

  # Claude Code local settings: merge top-level "claudeLocalSettings" from
  # projects.json into <project>/.claude/settings.local.json (personal,
  # per-machine, git-excluded below). Merge is per top-level key; object
  # values merge one level deep so unmanaged keys in an existing file survive.
  has_claude_settings="$(json_value 'const fs=require("fs"); const data=JSON.parse(fs.readFileSync(process.argv[1],"utf8")); console.log(data.claudeLocalSettings ? "yes" : "no");')"
  if [[ "$has_claude_settings" == "yes" ]]; then
    mkdir -p "$project_path/.claude"
    node -e '
      const fs = require("fs");
      const managed = JSON.parse(fs.readFileSync(process.argv[1], "utf8")).claudeLocalSettings;
      const target = process.argv[2];
      let existing = {};
      if (fs.existsSync(target)) {
        try { existing = JSON.parse(fs.readFileSync(target, "utf8")); } catch (e) {
          console.error("skip settings merge (existing file is not valid JSON): " + target);
          process.exit(0);
        }
      }
      for (const [key, value] of Object.entries(managed)) {
        if (value && typeof value === "object" && !Array.isArray(value)) {
          existing[key] = Object.assign({}, existing[key] || {}, value);
        } else {
          existing[key] = value;
        }
      }
      fs.writeFileSync(target, JSON.stringify(existing, null, 2) + "\n");
    ' "$PROJECTS_FILE" "$project_path/.claude/settings.local.json"
  fi

  if [[ -d "$project_path/.git" ]]; then
    exclude_file="$project_path/.git/info/exclude"
    touch "$exclude_file"
    if ! grep -qxF ".codex/" "$exclude_file"; then
      printf '\n.codex/\n' >> "$exclude_file"
    fi
    if ! grep -qxF "CLAUDE.local.md" "$exclude_file"; then
      printf 'CLAUDE.local.md\n' >> "$exclude_file"
    fi
    if ! grep -qxF "AGENTS.override.md" "$exclude_file"; then
      printf 'AGENTS.override.md\n' >> "$exclude_file"
    fi
    if [[ "$has_claude_settings" == "yes" ]] && ! grep -qxF ".claude/settings.local.json" "$exclude_file"; then
      printf '.claude/settings.local.json\n' >> "$exclude_file"
    fi
    if [[ "$skill_count" != "0" ]]; then
      for skill_path in "${installed_skills[@]}"; do
        if ! grep -qxF "$skill_path" "$exclude_file"; then
          printf '%s\n' "$skill_path" >> "$exclude_file"
        fi
      done
    fi
  fi

  echo "installed: $name"
  echo "  Codex:  $codex_output"
  echo "  Codex (discovered): $agents_output"
  echo "  Claude: $claude_output"
  if [[ "$has_claude_settings" == "yes" ]]; then
    echo "  Claude settings: $project_path/.claude/settings.local.json"
  fi
  if [[ "$skill_count" != "0" ]]; then
    echo "  Skills: ${installed_skills[*]}"
  fi
done
